@startuml
state DoorShut
state DoorOpen
state DoorOpenWithItem
state DoorShutWithItem
state ReadytoCook
state Cooking

[*] -> DoorShut

DoorShut -> DoorOpen : Door Opened
DoorShut -down-> DoorShut : Cancel

DoorOpen -> DoorShut : Door Closed
DoorOpen -> DoorOpenWithItem : Item Placed

DoorOpenWithItem -> DoorOpen : Item Removed
DoorOpenWithItem -> DoorShutWithItem : Door Closed with 0 time
DoorOpenWithItem -> ReadytoCook : Time Set

DoorShutWithItem -left-> DoorOpenWithItem : Door Opened
DoorShutWithItem -left-> ReadytoCook : Time Set

ReadytoCook -> DoorShutWithItem : Cancel
ReadytoCook -> DoorOpenWithItem : Door Opened
ReadytoCook -right-> Cooking : Start

Cooking -> DoorOpenWithItem : Door Opened
Cooking -> DoorShutWithItem : Timer Expired
Cooking -up-> ReadytoCook : Cancel
@enduml