@startuml
[*] --> HumanDriving
HumanDriving : Human Driving Mode

HumanDriving --> Autonomous : Power On
Autonomous : Autonomous Mode
Autonomous : <<submachine>>

Autonomous --> AutonomousIdle : Front Distance <= 10
AutonomousIdle : Autonomous Idle Mode

AutonomousIdle --> AutonomousActive : Front Distance > 10
AutonomousActive : Autonomous Active Mode

AutonomousActive --> HumanDriving : Human Steering Cmd
AutonomousActive --> HumanDriving : Brake Pressed

HumanDriving --> Autonomous : Front Distance > 10
HumanDriving --> AutonomousFinal : Power Off

AutonomousFinal : Auto Final State
@enduml