@startuml
[*] --> TurnOn : Start
state TurnOn
TurnOn --> fork1
state fork1 <<fork>>
fork1 --> AutoFocus
fork1 --> DetLight

state AutoFocus
AutoFocus --> choice1 : memFull=true

state DetLight
DetLight --> choice2 : <<GaStep>>{prob=0.4}

state choice1 <<choice>>
choice1 --> fork2
choice1 --> ChargedFlash : memFull=true

state ChargedFlash
ChargedFlash --> Junction3 : Charged=true

state fork2 <<fork>>
fork2 --> ChargedFlash

state Junction3 <<junction>>
Junction3 --> join2

state choice2 <<choice>>
choice2 --> join2 : sunny=false
choice2 --> join1 : sunny=true

state join2 <<join>>
join2 --> Junction2
join2 --> Flash : activated

state Flash
Flash --> Terminate

state join1 <<join>>
join1 --> Junction2

state Junction2 <<junction>>
Junction2 --> TakePicture

state TakePicture
TakePicture --> WriteMemory

state WriteMemory
WriteMemory --> Junction1

state Junction1 <<junction>>
Junction1 --> TurnOff : end

state TurnOff
TurnOff --> [*]
@enduml