@startuml
[*] --> TurnOn

state TurnOn {
[*] --> fork1: After (2 s)
}

TurnOn --> fork1
fork1 -down-> AutoFocus
fork1 -right-> DetLight

state AutoFocus {
[*] --> choice1: After (2 s)
choice1 --> Junction3: when (memFull=true)
}

state DetLight {
[*] --> choice2: After (1 s)
choice2 --> Join2: <<GaStep>>{prob=0.4}
choice2 --> Join1: [sunny=true]
}

fork1 -down-> choice3
choice3 --> ChargedFlash
ChargedFlash --> Junction3: when (Charged=true)

Junction3 --> Join2

state Join2 {
[*] --> Fork2
Fork2 --> Junction2
Fork2 --> Flash
Flash --> Terminate
}

Join1 --> Junction2

state Junction2 {
[*] --> TakePicture
TakePicture --> WriteMemory
WriteMemory --> Junction1
}

Junction1 --> TurnOff
TurnOff --> [*]
@enduml