@startuml

[*] --> Off
Off --> Operate : start

state Operate {
[*] --> Idle
Idle --> Accelerating_or_Cruising : accelerate
Accelerating_or_Cruising --> Braking : brake
Braking --> Idle : stop
Accelerating_or_Cruising --> Idle : stop
}

Operate --> Off : keyOff
Off --> [*] : shutdown

@enduml