@startuml
[*] --> SearchMission : Start Mission

state SearchMission {
  [*] --> Region1

  state Region1 {
    [*] --> Search
    Search --> Region2 : Finished Region1 Search
  }

  state Region2 {
    [*] --> Search
    Search --> Region3 : Finished Region2 Search
  }

  state Region3 {
    [*] --> Search
    Search --> [*] : Finished Region3 Search
  }
}

SearchMission --> FormationAdjust : Interception Detected

state FormationAdjust {
  [*] --> AdjustingFormation
  AdjustingFormation --> SearchMission : Finish Adjusting
}

SearchMission --> AttackState : Task Assignment Received

state AttackState {
  [*] --> Attacking
  Attacking --> SearchMission : Attack Finished / Decrease UAV swarm count
}
@enduml