@startuml

[*] --> PumpControl

state PumpControl {
state PumpRegion {
[*] --> PumpState
PumpState : Pump activated or controlled
}

state WaterRegion {
[*] --> WaterState
WaterState : Water flow control/monitoring
}

state MethaneRegion {
[*] --> MethaneState
MethaneState : Methane flow control/monitoring
}
}

@enduml