@startuml
[*] --> PoweredOn
PoweredOn --> Operate: start
state Operate {
[*] --> Idle
Idle --> AcceleratingOrCruising: user accelerating or cruising
Idle --> Braking: user braking
AcceleratingOrCruising --> Idle: user idle
AcceleratingOrCruising --> Braking: user braking
Braking --> Idle: user idle
Braking --> AcceleratingOrCruising: user accelerating or cruising
}
Operate --> [*] : keyOff
@enduml