@startuml
[*] --> DoorShut

DoorShut : Cancel
DoorShut --> DoorOpen : Door Opened

DoorOpen --> DoorShut : Close Door
DoorOpen --> DoorOpenWithItem : Place Item Inside

state DoorOpenWithItem {
    [*] --> DoorIdleWithItem

    DoorIdleWithItem --> DoorOpen : Remove Item
    DoorIdleWithItem --> DoorShutWithItem : Close Door with Zero Time
    DoorIdleWithItem --> ReadytoCook : Enter Cooking Time
}

state DoorShutWithItem {
    [*] --> ItemInside

    ItemInside --> DoorOpenWithItem : Open Door
    ItemInside --> ReadytoCook : Enter Cooking Time
}

state ReadytoCook {
    [*] --> WaitingToStart

    WaitingToStart --> DoorShutWithItem : Cancel
    WaitingToStart --> DoorOpenWithItem : Open Door
    WaitingToStart --> Cooking : Start
}

state Cooking {
    [*] --> ActiveCooking

    ActiveCooking --> DoorOpenWithItem : Open Door
    ActiveCooking --> DoorShutWithItem : Timer Expired
    ActiveCooking --> ReadytoCook : Cancel
}
@enduml