@startuml
[*] --> OffState
OffState : Off
OffState --> OperateState : start
OperateState : Operate

state OperateState {
[*] --> IdleRegion
state IdleRegion {
IdleState : Idle
}

state AccelerateRegion {
AcceleratingState : Accelerating
CruisingState : Cruising
}

state BrakeRegion {
BrakingState : Braking
}

IdleRegion --> AccelerateRegion : Accelerate
IdleRegion --> BrakeRegion : Brake
AccelerateRegion --> CruisingState : Reach Speed
AccelerateRegion --> BrakeRegion : Brake
CruisingState --> BrakeRegion : Brake
BrakeRegion --> IdleRegion : Stop
}

OperateState --> OffState : keyOff
@enduml