@startuml
[*] --> PumpControl

state PumpControl {
    [*] --> InitialState

    state PumpState {
        [*] --> RunningState : Activate Pump
        RunningState --> [*] : Deactivate Pump
    }

    --

    state WaterState {
        [*] --> MonitoringWaterFlow : Start Monitoring
        MonitoringWaterFlow --> [*] : Stop Monitoring
    }

    --

    state MethaneState {
        [*] --> MonitoringMethaneFlow : Start Monitoring
        MonitoringMethaneFlow --> [*] : Stop Monitoring
    }

    
}
@enduml