@startuml

[*] --> HumanDrivingMode : Power On

state HumanDrivingMode {
}

state AutonomousMode {
[*] --> SubState1
SubState1 --> SubState2
SubState2 --> SubState3
SubState3 --> [*]
}

HumanDrivingMode --> AutonomousMode : [front_distance > 10]

AutonomousMode --> HumanDrivingMode : human steering cmd\nor brake pressed\nor in (auto final)

HumanDrivingMode --> [*] : Power Off
AutonomousMode --> [*] : Power Off

@enduml